# Generated by Django 2.2.6 on 2020-01-01 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191231_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 1, 11, 4, 45, 704170, tzinfo=utc)),
        ),
    ]
