# Generated by Django 2.2.6 on 2020-01-01 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200101_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 1, 17, 27, 26, 905536, tzinfo=utc)),
        ),
    ]
