# Generated by Django 2.2.6 on 2020-01-04 00:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200101_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 4, 0, 35, 0, 882553, tzinfo=utc)),
        ),
    ]
